version: '3.9'

services:
  server:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'challenge-user'
      POSTGRES_PASSWORD: 'dOcFF29D4dxjyqF1BeGRA'
      POSTGRES_DB: 'challenge_bot'

    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:

